# Generated by Django 5.0.1 on 2024-02-14 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50, unique=True)),
                ('animal_name', models.CharField(max_length=100)),
                ('ear_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('sire_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dam_id', models.CharField(blank=True, max_length=50, null=True)),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('bull', 'Bull'), ('heifer', 'Heifer'), ('calf', 'Calf')], max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_age', models.IntegerField(blank=True, null=True)),
                ('weight_at_birth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age_at_first_service', models.IntegerField(blank=True, null=True)),
                ('weight_at_first_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
    ]
