# Generated by Django 5.0.1 on 2024-02-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_diagonisis_animalhealth_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_date', models.DateField()),
                ('morning_milk', models.DecimalField(decimal_places=2, max_digits=6)),
                ('afternoon_milk', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evening_milk', models.DecimalField(decimal_places=2, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.animal')),
            ],
        ),
    ]
